import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.Assert.assertEquals;

public class MainTest {
    private final PrintStream standardOut = System.out;
    private final ByteArrayOutputStream outputStreamCaptor = new ByteArrayOutputStream();

    @Before
    public void setUp() {
        System.setOut(new PrintStream(outputStreamCaptor));
    }

    @After
    public void tearDown() {
        System.setOut(standardOut);
    }

    @Test
    public void test() {
        //form problem
        simpleTest(10, 11, -2, -3);
        //generated by ChatGpt
        simpleTest(5, 8, 3, 2);
        simpleTest(-5, -8, -3, -2);
        simpleTest(5, 0, 8, 0);
        simpleTest(2147483647, 5, 8, -2147483648);
    }

    private void simpleTest(int int1, int int2, int int3, int int4) {
        //Set input stream
        String in = int1 + " " + int2 + " " + int3 + " " + int4;
        System.setIn(new ByteArrayInputStream(in.getBytes()));

        outputStreamCaptor.reset();
        Main.main(new String[]{""});

        //Construct expected result
        String expected = --int1 + " " + --int2 + " " + --int3 + " " + --int4;

        //Get the result
        String result = outputStreamCaptor.toString().trim();

        //Check the result
        String message = "For input:\r\n" + in + "\r\nThe output must be:\r\n" + expected + "\r\nActual output:\r\n" + result;
        assertEquals(message, expected, result);
    }
}